<?php
declare(strict_types=1);

date_default_timezone_set('America/New_York');

const REAL_FILE_NAME = 'install_team_chart_spreadsheet_border_fix_v001_20260920_032348pm.php';
const REAL_FILE_SHA256 = '392ab325a7263bcdcc1d5efae98e53a48d42b048954f2833f65980e0e80869de';
const REAL_FILE_B64 = 'PD9waHAKZGVjbGFyZShzdHJpY3RfdHlwZXM9MSk7CgovKioKICogaW5zdGFsbF90ZWFtX2NoYXJ0X3NwcmVhZHNoZWV0X2JvcmRlcl9maXhfdjAwMV8yMDI2MDkyMF8wMzIzNDhwbS5waHAKICoKICogVkVSU0lPTjogdjAwMQogKiBHRU5FUkFURUQ6IDkvMjAvMjAyNiAzOjIzOjQ4IHBtIEVUCiAqCiAqIFBVUlBPU0U6CiAqIC0gRml4ZXMgdGhlIG1pc3NpbmcgYm90dG9tIGJvcmRlciBhY3Jvc3MgdGhlIG1lcmdlZCBUZWFtIENoYXJ0IHNwcmVhZHNoZWV0IG5vdGUgcm93LgogKiAtIFVwZGF0ZXMgdGVhbV9jaGFydC5waHAgZnJvbSB2MDIzIHRvIHYwMjQuCiAqIC0gS2VlcHMgdGhlIHB1cmUtUEhQIFhMU1ggd3JpdGVyIGFuZCBhbGwgZXhwb3J0IGNvbnRlbnQvZm9ybWF0dGluZyB1bmNoYW5nZWQgb3RoZXJ3aXNlLgogKgogKiBTQUZFVFk6CiAqIC0gTW9kaWZpZXMgb25seSAvcHVibGljX2h0bWwvdGVhbV9jaGFydC5waHAuCiAqIC0gRXhwZWN0ZWQgYmFzZWxpbmU6IHYwMjMuCiAqIC0gQ2FuZGlkYXRlICsgaW5zdGFsbGVkIFBIUCBsaW50LgogKiAtIEJhY2t1cCArIHJvbGxiYWNrLgogKi8KCmRhdGVfZGVmYXVsdF90aW1lem9uZV9zZXQoJ0FtZXJpY2EvTmV3X1lvcmsnKTsKCmNvbnN0IEVYUEVDVEVEX1NPVVJDRV9WRVJTSU9OID0gJ3YwMjMnOwpjb25zdCBUQVJHRVRfVkVSU0lPTiA9ICd2MDI0JzsKCiRkb2NSb290ID0gcnRyaW0oKHN0cmluZykoJF9TRVJWRVJbJ0RPQ1VNRU5UX1JPT1QnXSA/PyBfX0RJUl9fKSwgJy9cXCcpOwokdGFyZ2V0ID0gJGRvY1Jvb3QgLiAnL3RlYW1fY2hhcnQucGhwJzsKJGJhY2t1cERpciA9ICRkb2NSb290IC4gJy9faW5zdGFsbGVyX2JhY2t1cHMvdGVhbV9jaGFydF9zcHJlYWRzaGVldF9ib3JkZXJfZml4XzIwMjYwOTIwXzAzMjM0OHBtJzsKJGJhY2t1cEZpbGUgPSAkYmFja3VwRGlyIC4gJy90ZWFtX2NoYXJ0LnBocCc7CgpmdW5jdGlvbiBoKCR2KTogc3RyaW5nCnsKICAgIHJldHVybiBodG1sc3BlY2lhbGNoYXJzKChzdHJpbmcpJHYsIEVOVF9RVU9URVMsICdVVEYtOCcpOwp9CgpmdW5jdGlvbiBsaW50X3BocF9maWxlKHN0cmluZyAkcGF0aCk6IGFycmF5CnsKICAgIGlmICghZnVuY3Rpb25fZXhpc3RzKCdzaGVsbF9leGVjJykpIHsKICAgICAgICByZXR1cm4gWydvayc9PmZhbHNlLCdvdXRwdXQnPT4nc2hlbGxfZXhlYygpIGlzIG5vdCBhdmFpbGFibGUuJ107CiAgICB9CgogICAgJG91dCA9IEBzaGVsbF9leGVjKCdwaHAgLWwgJyAuIGVzY2FwZXNoZWxsYXJnKCRwYXRoKSAuICcgMj4mMScpOwoKICAgIGlmICgkb3V0ID09PSBudWxsKSB7CiAgICAgICAgcmV0dXJuIFsnb2snPT5mYWxzZSwnb3V0cHV0Jz0+J1tOVUxMIHJldHVybmVkIGJ5IHNoZWxsX2V4ZWMoKV0nXTsKICAgIH0KCiAgICAkb3V0ID0gdHJpbSgoc3RyaW5nKSRvdXQpOwoKICAgIHJldHVybiBbCiAgICAgICAgJ29rJz0+c3RyaXBvcygkb3V0LCAnTm8gc3ludGF4IGVycm9ycyBkZXRlY3RlZCcpICE9PSBmYWxzZSwKICAgICAgICAnb3V0cHV0Jz0+JG91dCwKICAgIF07Cn0KCmZ1bmN0aW9uIGN1cnJlbnRfdmVyc2lvbihzdHJpbmcgJGNvbnRlbnQpOiBzdHJpbmcKewogICAgaWYgKHByZWdfbWF0Y2goJy9cKlxzKlZFUlNJT046XHMqKHZcZCspL2knLCAkY29udGVudCwgJG0pKSB7CiAgICAgICAgcmV0dXJuIChzdHJpbmcpJG1bMV07CiAgICB9CiAgICByZXR1cm4gJyc7Cn0KCmZ1bmN0aW9uIHJlcGxhY2Vfb25jZShzdHJpbmcgJHN1YmplY3QsIHN0cmluZyAkc2VhcmNoLCBzdHJpbmcgJHJlcGxhY2UsIHN0cmluZyAkbGFiZWwsIGFycmF5ICYkZXJyb3JzKTogc3RyaW5nCnsKICAgICRjb3VudCA9IHN1YnN0cl9jb3VudCgkc3ViamVjdCwgJHNlYXJjaCk7CgogICAgaWYgKCRjb3VudCAhPT0gMSkgewogICAgICAgICRlcnJvcnNbXSA9ICRsYWJlbCAuICc6IGV4cGVjdGVkIGV4YWN0bHkgMSBtYXRjaCwgZm91bmQgJyAuICRjb3VudCAuICcuJzsKICAgICAgICByZXR1cm4gJHN1YmplY3Q7CiAgICB9CgogICAgJHBvcyA9IHN0cnBvcygkc3ViamVjdCwgJHNlYXJjaCk7CgogICAgaWYgKCRwb3MgPT09IGZhbHNlKSB7CiAgICAgICAgJGVycm9yc1tdID0gJGxhYmVsIC4gJzogYW5jaG9yIG5vdCBmb3VuZC4nOwogICAgICAgIHJldHVybiAkc3ViamVjdDsKICAgIH0KCiAgICByZXR1cm4gc3Vic3RyKCRzdWJqZWN0LCAwLCAkcG9zKQogICAgICAgIC4gJHJlcGxhY2UKICAgICAgICAuIHN1YnN0cigkc3ViamVjdCwgJHBvcyArIHN0cmxlbigkc2VhcmNoKSk7Cn0KCmZ1bmN0aW9uIGJ1aWxkX2NhbmRpZGF0ZShzdHJpbmcgJHNvdXJjZSwgYXJyYXkgJiRlcnJvcnMpOiBzdHJpbmcKewogICAgJG91dCA9ICRzb3VyY2U7CgogICAgJG91dCA9IHJlcGxhY2Vfb25jZSgKICAgICAgICAkb3V0LAogICAgICAgICcgKiBWRVJTSU9OOiB2MDIzJywKICAgICAgICAnICogVkVSU0lPTjogdjAyNCcsCiAgICAgICAgJ1ZlcnNpb24gaGVhZGVyJywKICAgICAgICAkZXJyb3JzCiAgICApOwoKICAgIGlmIChwcmVnX21hdGNoKCcvIFwqIExBU1QgTU9ESUZJRUQ6IC4qPyBFVFxSLycsICRvdXQsICRtKSkgewogICAgICAgICRvdXQgPSBzdHJfcmVwbGFjZSgKICAgICAgICAgICAgJG1bMF0sCiAgICAgICAgICAgICcgKiBMQVNUIE1PRElGSUVEOiA5LzIwLzIwMjYgMzoyMzo0OCBwbSBFVCcgLiBQSFBfRU9MLAogICAgICAgICAgICAkb3V0CiAgICAgICAgKTsKICAgIH0gZWxzZSB7CiAgICAgICAgJGVycm9yc1tdID0gJ0xBU1QgTU9ESUZJRUQgaGVhZGVyIG5vdCBmb3VuZC4nOwogICAgfQoKICAgICRjaGFuZ2Vsb2dBbmNob3IgPSAiICogQ0hBTkdFTE9HOlxuICpcbiI7CiAgICAkY2hhbmdlbG9nSW5zZXJ0ID0gIiAqIENIQU5HRUxPRzpcbiAqXG4iCiAgICAgICAgLiAiICogdjAyNCAoOS8yMC8yMDI2IDM6MjM6NDggcG0gRVQpXG4iCiAgICAgICAgLiAiICogLSBFWFBPUlQgRklYOiBBcHBsaWVzIHRoZSBub3RlLXJvdyBib3JkZXIgc3R5bGUgdG8gYWxsIHNldmVuIGNlbGxzIGJlZm9yZSBtZXJnaW5nIEE6RyBpbiB0aGUgWExTWCBmb290ZXIuXG4iCiAgICAgICAgLiAiICogLSBSRVNVTFQ6IFJlc3RvcmVzIHRoZSB2aXNpYmxlIGJvdHRvbSBib3JkZXIgYWNyb3NzIHRoZSBmdWxsIHdpZHRoIG9mIHRoZSBmaW5hbCBwZWFjaCBub3RlIHJvdyBpbiBFeGNlbC5cbiIKICAgICAgICAuICIgKiAtIFBSRVNFUlZFOiBQdXJlLVBIUCBYTFNYIHdyaXRlciwgdGl0bGUvaGVhZGVyL2RhdGEgY29sb3JzLCBub3Rlcywgd2lkdGhzLCBmcm96ZW4gcm93cywgcHJpbnQgYmVoYXZpb3IsIG5hdmlnYXRpb24sIHRoZW1lcywgTFAvUkQgZGlzcGxheSwgYW5kIERCIHF1ZXJpZXMgdW5jaGFuZ2VkLlxuIgogICAgICAgIC4gIiAqXG4iOwoKICAgICRvdXQgPSByZXBsYWNlX29uY2UoCiAgICAgICAgJG91dCwKICAgICAgICAkY2hhbmdlbG9nQW5jaG9yLAogICAgICAgICRjaGFuZ2Vsb2dJbnNlcnQsCiAgICAgICAgJ0NoYW5nZWxvZyBhbmNob3InLAogICAgICAgICRlcnJvcnMKICAgICk7CgogICAgJG9sZEJsb2NrID0gPDw8J1BIUEJMT0NLJwogICAgZm9yZWFjaCAoJG5vdGVzIGFzICRub3RlKSB7CiAgICAgICAgJHRleHQgPSAoc3RyaW5nKSgoJG5vdGVbJ21hcmtlciddID8/ICcnKSAuICcgJyAuICgkbm90ZVsndGV4dCddID8/ICcnKSk7CiAgICAgICAgJGNlbGxzQnlSb3dbJHJvd051bV1bXSA9IHRjX3hsc3hfY2VsbF94bWwoJ0EnIC4gJHJvd051bSwgJHRleHQsIDgpOwogICAgICAgICRtZXJnZVJhbmdlc1tdID0gJ0EnIC4gJHJvd051bSAuICc6RycgLiAkcm93TnVtOwogICAgICAgICRyb3dOdW0rKzsKICAgIH0KUEhQQkxPQ0s7CgogICAgJG5ld0Jsb2NrID0gPDw8J1BIUEJMT0NLJwogICAgZm9yZWFjaCAoJG5vdGVzIGFzICRub3RlKSB7CiAgICAgICAgJHRleHQgPSAoc3RyaW5nKSgoJG5vdGVbJ21hcmtlciddID8/ICcnKSAuICcgJyAuICgkbm90ZVsndGV4dCddID8/ICcnKSk7CgogICAgICAgIC8vIEtlZXAgQSBhcyB0aGUgdmlzaWJsZSBtZXJnZWQtY2VsbCB2YWx1ZSwgYnV0IGFsc28gY3JlYXRlIHN0eWxlZAogICAgICAgIC8vIGJsYW5rIGNlbGxzIEI6RyBiZWZvcmUgbWVyZ2luZyBzbyBFeGNlbCBoYXMgdGhlIGJvcmRlciBzdHlsZQogICAgICAgIC8vIGFjcm9zcyB0aGUgZW50aXJlIHBlcmltZXRlciBvZiB0aGUgbWVyZ2VkIGZvb3RlciByb3cuCiAgICAgICAgJGNlbGxzQnlSb3dbJHJvd051bV1bXSA9IHRjX3hsc3hfY2VsbF94bWwoJ0EnIC4gJHJvd051bSwgJHRleHQsIDgpOwoKICAgICAgICBmb3IgKCRjb2wgPSAyOyAkY29sIDw9IDc7ICRjb2wrKykgewogICAgICAgICAgICAkY2VsbHNCeVJvd1skcm93TnVtXVtdID0gdGNfeGxzeF9jZWxsX3htbCgKICAgICAgICAgICAgICAgIHRjX3hsc3hfY29sX2xldHRlcigkY29sKSAuICRyb3dOdW0sCiAgICAgICAgICAgICAgICAnJywKICAgICAgICAgICAgICAgIDgKICAgICAgICAgICAgKTsKICAgICAgICB9CgogICAgICAgICRtZXJnZVJhbmdlc1tdID0gJ0EnIC4gJHJvd051bSAuICc6RycgLiAkcm93TnVtOwogICAgICAgICRyb3dOdW0rKzsKICAgIH0KUEhQQkxPQ0s7CgogICAgJG91dCA9IHJlcGxhY2Vfb25jZSgKICAgICAgICAkb3V0LAogICAgICAgICRvbGRCbG9jaywKICAgICAgICAkbmV3QmxvY2ssCiAgICAgICAgJ1hMU1ggbm90ZS1yb3cgYmxvY2snLAogICAgICAgICRlcnJvcnMKICAgICk7CgogICAgcmV0dXJuICRvdXQ7Cn0KCmZ1bmN0aW9uIGNhbmRpZGF0ZV9saW50KHN0cmluZyAkY2FuZGlkYXRlLCBzdHJpbmcgJHRhcmdldERpcik6IGFycmF5CnsKICAgICR0bXAgPSBAdGVtcG5hbSgkdGFyZ2V0RGlyLCAnLm1ybF90ZWFtX2NoYXJ0X2JvcmRlcl8nKTsKCiAgICBpZiAoJHRtcCA9PT0gZmFsc2UpIHsKICAgICAgICAkdG1wID0gQHRlbXBuYW0oc3lzX2dldF90ZW1wX2RpcigpLCAnbXJsX3RlYW1fY2hhcnRfYm9yZGVyXycpOwogICAgfQoKICAgIGlmICgkdG1wID09PSBmYWxzZSkgewogICAgICAgIHJldHVybiBbJ29rJz0+ZmFsc2UsJ291dHB1dCc9PidDb3VsZCBub3QgY3JlYXRlIHRlbXBvcmFyeSBsaW50IGZpbGUuJ107CiAgICB9CgogICAgaWYgKEBmaWxlX3B1dF9jb250ZW50cygkdG1wLCAkY2FuZGlkYXRlLCBMT0NLX0VYKSA9PT0gZmFsc2UpIHsKICAgICAgICBAdW5saW5rKCR0bXApOwogICAgICAgIHJldHVybiBbJ29rJz0+ZmFsc2UsJ291dHB1dCc9PidDb3VsZCBub3Qgd3JpdGUgdGVtcG9yYXJ5IGxpbnQgZmlsZS4nXTsKICAgIH0KCiAgICAkbGludCA9IGxpbnRfcGhwX2ZpbGUoJHRtcCk7CiAgICBAdW5saW5rKCR0bXApOwoKICAgIHJldHVybiAkbGludDsKfQoKJGFjdGlvbiA9IChzdHJpbmcpKCRfUE9TVFsnYWN0aW9uJ10gPz8gJycpOwokbWVzc2FnZSA9ICcnOwokbWVzc2FnZUNsYXNzID0gJ2luZm8nOwoKJHRhcmdldEV4aXN0cyA9IGlzX2ZpbGUoJHRhcmdldCk7CiR0YXJnZXRXcml0YWJsZSA9ICR0YXJnZXRFeGlzdHMgJiYgaXNfd3JpdGFibGUoJHRhcmdldCk7CiRzb3VyY2UgPSAkdGFyZ2V0RXhpc3RzID8gKHN0cmluZylAZmlsZV9nZXRfY29udGVudHMoJHRhcmdldCkgOiAnJzsKJHZlcnNpb24gPSAkc291cmNlICE9PSAnJyA/IGN1cnJlbnRfdmVyc2lvbigkc291cmNlKSA6ICcnOwokYWxyZWFkeUluc3RhbGxlZCA9ICgkdmVyc2lvbiA9PT0gVEFSR0VUX1ZFUlNJT04pOwoKJGVycm9ycyA9IFtdOwokY2FuZGlkYXRlID0gJyc7CiRjYW5kaWRhdGVMaW50ID0gWydvayc9PmZhbHNlLCdvdXRwdXQnPT4nTm90IHJ1bi4nXTsKCmlmICgkdGFyZ2V0RXhpc3RzICYmICR2ZXJzaW9uID09PSBFWFBFQ1RFRF9TT1VSQ0VfVkVSU0lPTikgewogICAgJGNhbmRpZGF0ZSA9IGJ1aWxkX2NhbmRpZGF0ZSgkc291cmNlLCAkZXJyb3JzKTsKCiAgICBpZiAoZW1wdHkoJGVycm9ycykpIHsKICAgICAgICAkY2FuZGlkYXRlTGludCA9IGNhbmRpZGF0ZV9saW50KCRjYW5kaWRhdGUsIGRpcm5hbWUoJHRhcmdldCkpOwogICAgfQp9CgokaW5zdGFsbGVkTGludCA9ICR0YXJnZXRFeGlzdHMKICAgID8gbGludF9waHBfZmlsZSgkdGFyZ2V0KQogICAgOiBbJ29rJz0+ZmFsc2UsJ291dHB1dCc9PidUYXJnZXQgbWlzc2luZy4nXTsKCiRiYWNrdXBFeGlzdHMgPSBpc19maWxlKCRiYWNrdXBGaWxlKTsKCiRjYW5BcHBseSA9CiAgICAkdGFyZ2V0RXhpc3RzCiAgICAmJiAkdGFyZ2V0V3JpdGFibGUKICAgICYmICR2ZXJzaW9uID09PSBFWFBFQ1RFRF9TT1VSQ0VfVkVSU0lPTgogICAgJiYgZW1wdHkoJGVycm9ycykKICAgICYmICFlbXB0eSgkY2FuZGlkYXRlTGludFsnb2snXSk7CgppZiAoJGFjdGlvbiA9PT0gJ2FwcGx5JykgewogICAgaWYgKCEkY2FuQXBwbHkpIHsKICAgICAgICAkbWVzc2FnZSA9ICdBcHBseSBibG9ja2VkOiBwcmVmbGlnaHQgaXMgbm90IGZ1bGx5IFBBU1MuJzsKICAgICAgICAkbWVzc2FnZUNsYXNzID0gJ2JhZCc7CiAgICB9IGVsc2UgewogICAgICAgIGlmICghaXNfZGlyKCRiYWNrdXBEaXIpICYmICFAbWtkaXIoJGJhY2t1cERpciwgMDc1NSwgdHJ1ZSkgJiYgIWlzX2RpcigkYmFja3VwRGlyKSkgewogICAgICAgICAgICAkbWVzc2FnZSA9ICdBcHBseSBibG9ja2VkOiBiYWNrdXAgZGlyZWN0b3J5IGNvdWxkIG5vdCBiZSBjcmVhdGVkLic7CiAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICB9IGVsc2VpZiAoaXNfZmlsZSgkYmFja3VwRmlsZSkpIHsKICAgICAgICAgICAgJG1lc3NhZ2UgPSAnQXBwbHkgYmxvY2tlZDogYmFja3VwIGFscmVhZHkgZXhpc3RzIGZvciB0aGlzIGluc3RhbGxlciBydW4uJzsKICAgICAgICAgICAgJG1lc3NhZ2VDbGFzcyA9ICdiYWQnOwogICAgICAgIH0gZWxzZWlmICghQGNvcHkoJHRhcmdldCwgJGJhY2t1cEZpbGUpKSB7CiAgICAgICAgICAgICRtZXNzYWdlID0gJ0FwcGx5IGJsb2NrZWQ6IGJhY2t1cCBjb3VsZCBub3QgYmUgY3JlYXRlZC4nOwogICAgICAgICAgICAkbWVzc2FnZUNsYXNzID0gJ2JhZCc7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgQGNobW9kKCRiYWNrdXBGaWxlLCAwNjQ0KTsKCiAgICAgICAgICAgICR0bXBUYXJnZXQgPSAkdGFyZ2V0IC4gJy5tcmxfdG1wXycgLiB1bmlxaWQoJycsIHRydWUpOwoKICAgICAgICAgICAgaWYgKEBmaWxlX3B1dF9jb250ZW50cygkdG1wVGFyZ2V0LCAkY2FuZGlkYXRlLCBMT0NLX0VYKSA9PT0gZmFsc2UpIHsKICAgICAgICAgICAgICAgIEB1bmxpbmsoJHRtcFRhcmdldCk7CiAgICAgICAgICAgICAgICAkbWVzc2FnZSA9ICdBcHBseSBmYWlsZWQ6IHRlbXBvcmFyeSB0YXJnZXQgY291bGQgbm90IGJlIHdyaXR0ZW4uJzsKICAgICAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgICAgIEBjaG1vZCgkdG1wVGFyZ2V0LCAwNjQ0KTsKICAgICAgICAgICAgICAgICR0bXBMaW50ID0gbGludF9waHBfZmlsZSgkdG1wVGFyZ2V0KTsKCiAgICAgICAgICAgICAgICBpZiAoZW1wdHkoJHRtcExpbnRbJ29rJ10pKSB7CiAgICAgICAgICAgICAgICAgICAgQHVubGluaygkdG1wVGFyZ2V0KTsKICAgICAgICAgICAgICAgICAgICAkbWVzc2FnZSA9ICdBcHBseSBibG9ja2VkOiB0ZW1wb3JhcnkgcmVwbGFjZW1lbnQgZmFpbGVkIFBIUCBsaW50LiAnIC4gJHRtcExpbnRbJ291dHB1dCddOwogICAgICAgICAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICAgICAgICAgIH0gZWxzZWlmICghQHJlbmFtZSgkdG1wVGFyZ2V0LCAkdGFyZ2V0KSkgewogICAgICAgICAgICAgICAgICAgIEB1bmxpbmsoJHRtcFRhcmdldCk7CiAgICAgICAgICAgICAgICAgICAgJG1lc3NhZ2UgPSAnQXBwbHkgZmFpbGVkOiBhdG9taWMgcmVwbGFjZW1lbnQgY291bGQgbm90IGJlIGNvbXBsZXRlZC4nOwogICAgICAgICAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgQGNobW9kKCR0YXJnZXQsIDA2NDQpOwogICAgICAgICAgICAgICAgICAgICRuZXdMaW50ID0gbGludF9waHBfZmlsZSgkdGFyZ2V0KTsKCiAgICAgICAgICAgICAgICAgICAgaWYgKGVtcHR5KCRuZXdMaW50WydvayddKSkgewogICAgICAgICAgICAgICAgICAgICAgICBAY29weSgkYmFja3VwRmlsZSwgJHRhcmdldCk7CiAgICAgICAgICAgICAgICAgICAgICAgIEBjaG1vZCgkdGFyZ2V0LCAwNjQ0KTsKICAgICAgICAgICAgICAgICAgICAgICAgJG1lc3NhZ2UgPSAnSW5zdGFsbGVkIGZpbGUgZmFpbGVkIGxpbnQgYW5kIGJhY2t1cCB3YXMgYXV0b21hdGljYWxseSByZXN0b3JlZC4gJyAuICRuZXdMaW50WydvdXRwdXQnXTsKICAgICAgICAgICAgICAgICAgICAgICAgJG1lc3NhZ2VDbGFzcyA9ICdiYWQnOwogICAgICAgICAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgICAgICRtZXNzYWdlID0gJ1BBU1Mg4oCUIHRlYW1fY2hhcnQucGhwIHYwMjQgaW5zdGFsbGVkIGFuZCBwYXNzZWQgUEhQIGxpbnQuJzsKICAgICAgICAgICAgICAgICAgICAgICAgJG1lc3NhZ2VDbGFzcyA9ICdnb29kJzsKICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0KCmlmICgkYWN0aW9uID09PSAncm9sbGJhY2snKSB7CiAgICBpZiAoIWlzX2ZpbGUoJGJhY2t1cEZpbGUpKSB7CiAgICAgICAgJG1lc3NhZ2UgPSAnUm9sbGJhY2sgdW5hdmFpbGFibGU6IGJhY2t1cCBub3QgZm91bmQuJzsKICAgICAgICAkbWVzc2FnZUNsYXNzID0gJ2JhZCc7CiAgICB9IGVsc2UgewogICAgICAgICRiYWNrdXBMaW50ID0gbGludF9waHBfZmlsZSgkYmFja3VwRmlsZSk7CgogICAgICAgIGlmIChlbXB0eSgkYmFja3VwTGludFsnb2snXSkpIHsKICAgICAgICAgICAgJG1lc3NhZ2UgPSAnUm9sbGJhY2sgYmxvY2tlZDogYmFja3VwIGZhaWxlZCBsaW50LiAnIC4gJGJhY2t1cExpbnRbJ291dHB1dCddOwogICAgICAgICAgICAkbWVzc2FnZUNsYXNzID0gJ2JhZCc7CiAgICAgICAgfSBlbHNlaWYgKCFAY29weSgkYmFja3VwRmlsZSwgJHRhcmdldCkpIHsKICAgICAgICAgICAgJG1lc3NhZ2UgPSAnUm9sbGJhY2sgZmFpbGVkOiBiYWNrdXAgY291bGQgbm90IGJlIHJlc3RvcmVkLic7CiAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBAY2htb2QoJHRhcmdldCwgMDY0NCk7CiAgICAgICAgICAgICRyZXN0b3JlZExpbnQgPSBsaW50X3BocF9maWxlKCR0YXJnZXQpOwoKICAgICAgICAgICAgaWYgKGVtcHR5KCRyZXN0b3JlZExpbnRbJ29rJ10pKSB7CiAgICAgICAgICAgICAgICAkbWVzc2FnZSA9ICdSb2xsYmFjayBjb3B5IGNvbXBsZXRlZCwgYnV0IHJlc3RvcmVkIGZpbGUgZmFpbGVkIGxpbnQuICcgLiAkcmVzdG9yZWRMaW50WydvdXRwdXQnXTsKICAgICAgICAgICAgICAgICRtZXNzYWdlQ2xhc3MgPSAnYmFkJzsKICAgICAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgICAgICRtZXNzYWdlID0gJ1JvbGxiYWNrIGNvbXBsZXRlIOKAlCB0ZWFtX2NoYXJ0LnBocCB2MDIzIHJlc3RvcmVkIGFuZCBsaW50IHBhc3NlZC4nOwogICAgICAgICAgICAgICAgJG1lc3NhZ2VDbGFzcyA9ICdnb29kJzsKICAgICAgICAgICAgfQogICAgICAgIH0KICAgIH0KfQoKJHNvdXJjZSA9IGlzX2ZpbGUoJHRhcmdldCkgPyAoc3RyaW5nKUBmaWxlX2dldF9jb250ZW50cygkdGFyZ2V0KSA6ICcnOwokdmVyc2lvbiA9ICRzb3VyY2UgIT09ICcnID8gY3VycmVudF92ZXJzaW9uKCRzb3VyY2UpIDogJyc7CiRhbHJlYWR5SW5zdGFsbGVkID0gKCR2ZXJzaW9uID09PSBUQVJHRVRfVkVSU0lPTik7CiRiYWNrdXBFeGlzdHMgPSBpc19maWxlKCRiYWNrdXBGaWxlKTsKJGluc3RhbGxlZExpbnQgPSBpc19maWxlKCR0YXJnZXQpCiAgICA/IGxpbnRfcGhwX2ZpbGUoJHRhcmdldCkKICAgIDogWydvayc9PmZhbHNlLCdvdXRwdXQnPT4nVGFyZ2V0IG1pc3NpbmcuJ107Cgo/Pgo8IWRvY3R5cGUgaHRtbD4KPGh0bWwgbGFuZz0iZW4iPgo8aGVhZD4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgo8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLGluaXRpYWwtc2NhbGU9MSI+Cjx0aXRsZT5NUkwgVGVhbSBDaGFydCBTcHJlYWRzaGVldCBCb3JkZXIgRml4PC90aXRsZT4KPHN0eWxlPgo6cm9vdHtjb2xvci1zY2hlbWU6ZGFyazstLWJnOiMxMDEwMTA7LS1wYW5lbDojMWIxYjFiOy0tbGluZTojM2QzZDNkOy0tdGV4dDojZWVlOy0tbXV0ZWQ6I2FhYTstLWdvb2Q6IzY2ZGY4ZDstLWJhZDojZmY3NDc0Oy0tZ29sZDojZjJjOThlfQoqe2JveC1zaXppbmc6Ym9yZGVyLWJveH0KYm9keXttYXJnaW46MDtwYWRkaW5nOjIycHg7YmFja2dyb3VuZDp2YXIoLS1iZyk7Y29sb3I6dmFyKC0tdGV4dCk7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWZ9Ci53cmFwe21heC13aWR0aDoxMTAwcHg7bWFyZ2luOjAgYXV0b30KaDF7bWFyZ2luOjAgMCA2cHg7Y29sb3I6dmFyKC0tZ29sZCl9Cmgye21hcmdpbjowIDAgMTBweH0KLmNhcmR7bWFyZ2luOjE0cHggMDtwYWRkaW5nOjE2cHg7YmFja2dyb3VuZDp2YXIoLS1wYW5lbCk7Ym9yZGVyOjFweCBzb2xpZCB2YXIoLS1saW5lKTtib3JkZXItcmFkaXVzOjE0cHh9Ci5ub3RpY2V7bWFyZ2luOjE0cHggMDtwYWRkaW5nOjEycHggMTRweDtib3JkZXItcmFkaXVzOjEwcHg7Ym9yZGVyOjFweCBzb2xpZCAjMzY1MDZmO2JhY2tncm91bmQ6IzE0MjAzM30KLm5vdGljZS5nb29ke2JvcmRlci1jb2xvcjojMzI3YTRiO2JhY2tncm91bmQ6IzEzMjcxYTtjb2xvcjojYThlZmJmfQoubm90aWNlLmJhZHtib3JkZXItY29sb3I6Izk4M2YzZjtiYWNrZ3JvdW5kOiMyYTE1MTU7Y29sb3I6I2ZmYjBiMH0KLnBhc3N7Y29sb3I6dmFyKC0tZ29vZCk7Zm9udC13ZWlnaHQ6ODAwfS5mYWlse2NvbG9yOnZhcigtLWJhZCk7Zm9udC13ZWlnaHQ6ODAwfS5tdXRlZHtjb2xvcjp2YXIoLS1tdXRlZCl9CmNvZGV7YmFja2dyb3VuZDojMjgyODI4O3BhZGRpbmc6MnB4IDVweDtib3JkZXItcmFkaXVzOjVweH0KdGFibGV7d2lkdGg6MTAwJTtib3JkZXItY29sbGFwc2U6Y29sbGFwc2V9CnRoLHRke3BhZGRpbmc6OXB4IDEwcHg7Ym9yZGVyLWJvdHRvbToxcHggc29saWQgIzMzMzt0ZXh0LWFsaWduOmxlZnQ7dmVydGljYWwtYWxpZ246dG9wfQp0aHtjb2xvcjp2YXIoLS1nb2xkKX0KLmJ1dHRvbnN7ZGlzcGxheTpmbGV4O2ZsZXgtd3JhcDp3cmFwO2dhcDoxMHB4O21hcmdpbi10b3A6MTRweH0KYnV0dG9uLC5idG57Ym9yZGVyOjA7Ym9yZGVyLXJhZGl1czo5cHg7cGFkZGluZzoxMHB4IDE2cHg7Y29sb3I6I2ZmZjtmb250LXdlaWdodDo3MDA7Y3Vyc29yOnBvaW50ZXI7dGV4dC1kZWNvcmF0aW9uOm5vbmU7ZGlzcGxheTppbmxpbmUtYmxvY2s7Zm9udC1zaXplOjE0cHh9Ci5hcHBseXtiYWNrZ3JvdW5kOiMyNDhjNGJ9Lm5ldXRyYWx7YmFja2dyb3VuZDojMjc2ZmNhfS5yb2xsYmFja3tiYWNrZ3JvdW5kOiNhODM0MzR9CmJ1dHRvbjpkaXNhYmxlZHtvcGFjaXR5Oi4zODtjdXJzb3I6bm90LWFsbG93ZWR9CnVse2xpbmUtaGVpZ2h0OjEuNX0KPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KPGRpdiBjbGFzcz0id3JhcCI+CiAgICA8aDE+TVJMIFRlYW0gQ2hhcnQgU3ByZWFkc2hlZXQgQm9yZGVyIEZpeDwvaDE+CiAgICA8ZGl2IGNsYXNzPSJtdXRlZCI+SW5zdGFsbGVyIHYwMDEgwrcgZ2VuZXJhdGVkIDkvMjAvMjAyNiAzOjIzOjQ4IHBtIEVUPC9kaXY+CgogICAgPD9waHAgaWYgKCRtZXNzYWdlICE9PSAnJyk6ID8+CiAgICAgICAgPGRpdiBjbGFzcz0ibm90aWNlIDw/cGhwIGVjaG8gaCgkbWVzc2FnZUNsYXNzKTsgPz4iPjw/cGhwIGVjaG8gaCgkbWVzc2FnZSk7ID8+PC9kaXY+CiAgICA8P3BocCBlbmRpZjsgPz4KCiAgICA8ZGl2IGNsYXNzPSJjYXJkIj4KICAgICAgICA8aDI+V2hhdCB0aGlzIGZpeGVzPC9oMj4KICAgICAgICA8dWw+CiAgICAgICAgICAgIDxsaT5SZXN0b3JlcyB0aGUgbWlzc2luZyBib3R0b20gYm9yZGVyIGFjcm9zcyB0aGUgZnVsbCBtZXJnZWQgcGVhY2ggbm90ZSByb3cgaW4gdGhlIFRlYW0gQ2hhcnQgWExTWC48L2xpPgogICAgICAgICAgICA8bGk+U3R5bGVzIGNlbGxzIEE6RyBiZWZvcmUgdGhlIG5vdGUgcm93IGlzIG1lcmdlZCwgc28gRXhjZWwgcmVuZGVycyB0aGUgZnVsbCBvdXRlciBib3JkZXIuPC9saT4KICAgICAgICAgICAgPGxpPk5vIHNwcmVhZHNoZWV0IGRhdGEsIGNvbG9ycywgd2lkdGhzLCBub3RlcywgZmlsZW5hbWVzLCBvciBwcmludCBiZWhhdmlvciBjaGFuZ2VzLjwvbGk+CiAgICAgICAgPC91bD4KICAgIDwvZGl2PgoKICAgIDxkaXYgY2xhc3M9ImNhcmQiPgogICAgICAgIDxoMj5QcmVmbGlnaHQ8L2gyPgogICAgICAgIDx0YWJsZT4KICAgICAgICAgICAgPHRyPjx0aD5DaGVjazwvdGg+PHRoPlN0YXR1czwvdGg+PHRoPkRldGFpbDwvdGg+PC90cj4KICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgPHRkPlRhcmdldCBleGlzdHM8L3RkPgogICAgICAgICAgICAgICAgPHRkIGNsYXNzPSI8P3BocCBlY2hvICR0YXJnZXRFeGlzdHMgPyAncGFzcycgOiAnZmFpbCc7ID8+Ij48P3BocCBlY2hvICR0YXJnZXRFeGlzdHMgPyAnUEFTUycgOiAnRkFJTCc7ID8+PC90ZD4KICAgICAgICAgICAgICAgIDx0ZD48Y29kZT48P3BocCBlY2hvIGgoJHRhcmdldCk7ID8+PC9jb2RlPjwvdGQ+CiAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgIDx0ZD5UYXJnZXQgd3JpdGFibGU8L3RkPgogICAgICAgICAgICAgICAgPHRkIGNsYXNzPSI8P3BocCBlY2hvICR0YXJnZXRXcml0YWJsZSA/ICdwYXNzJyA6ICdmYWlsJzsgPz4iPjw/cGhwIGVjaG8gJHRhcmdldFdyaXRhYmxlID8gJ1BBU1MnIDogJ0ZBSUwnOyA/PjwvdGQ+CiAgICAgICAgICAgICAgICA8dGQ+PD9waHAgZWNobyAkdGFyZ2V0V3JpdGFibGUgPyAnV3JpdGFibGUnIDogJ05vdCB3cml0YWJsZSc7ID8+PC90ZD4KICAgICAgICAgICAgPC90cj4KICAgICAgICAgICAgPHRyPgogICAgICAgICAgICAgICAgPHRkPkN1cnJlbnQgdmVyc2lvbjwvdGQ+CiAgICAgICAgICAgICAgICA8dGQgY2xhc3M9Ijw/cGhwIGVjaG8gKCR2ZXJzaW9uID09PSBFWFBFQ1RFRF9TT1VSQ0VfVkVSU0lPTiB8fCAkYWxyZWFkeUluc3RhbGxlZCkgPyAncGFzcycgOiAnZmFpbCc7ID8+Ij4KICAgICAgICAgICAgICAgICAgICA8P3BocCBlY2hvICgkdmVyc2lvbiA9PT0gRVhQRUNURURfU09VUkNFX1ZFUlNJT04gfHwgJGFscmVhZHlJbnN0YWxsZWQpID8gJ1BBU1MnIDogJ0ZBSUwnOyA/PgogICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDx0ZD5EZXRlY3RlZCA8c3Ryb25nPjw/cGhwIGVjaG8gaCgkdmVyc2lvbiAhPT0gJycgPyAkdmVyc2lvbiA6ICcodW5rbm93biknKTsgPz48L3N0cm9uZz47IGV4cGVjdGVkIHYwMjMgYmVmb3JlIEFwcGx5LCBvciB2MDI0IGFmdGVyIEFwcGx5LjwvdGQ+CiAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgIDx0ZD5QYXRjaCBzaWduYXR1cmVzPC90ZD4KICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz0iPD9waHAgZWNobyAoJGFscmVhZHlJbnN0YWxsZWQgfHwgZW1wdHkoJGVycm9ycykpID8gJ3Bhc3MnIDogJ2ZhaWwnOyA/PiI+CiAgICAgICAgICAgICAgICAgICAgPD9waHAgZWNobyAoJGFscmVhZHlJbnN0YWxsZWQgfHwgZW1wdHkoJGVycm9ycykpID8gJ1BBU1MnIDogJ0ZBSUwnOyA/PgogICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDx0ZD48P3BocCBlY2hvIGgoJGFscmVhZHlJbnN0YWxsZWQgPyAndjAyNCBhbHJlYWR5IGluc3RhbGxlZC4nIDogKGVtcHR5KCRlcnJvcnMpID8gJ0V4cGVjdGVkIHYwMjMgWExTWCBub3RlLXJvdyBhbmNob3IgZm91bmQgZXhhY3RseSBvbmNlLicgOiBpbXBsb2RlKCcgfCAnLCAkZXJyb3JzKSkpOyA/PjwvdGQ+CiAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgIDx0ZD5DYW5kaWRhdGUgUEhQIGxpbnQ8L3RkPgogICAgICAgICAgICAgICAgPHRkIGNsYXNzPSI8P3BocCBlY2hvICgkYWxyZWFkeUluc3RhbGxlZCB8fCAhZW1wdHkoJGNhbmRpZGF0ZUxpbnRbJ29rJ10pKSA/ICdwYXNzJyA6ICdmYWlsJzsgPz4iPgogICAgICAgICAgICAgICAgICAgIDw/cGhwIGVjaG8gKCRhbHJlYWR5SW5zdGFsbGVkIHx8ICFlbXB0eSgkY2FuZGlkYXRlTGludFsnb2snXSkpID8gJ1BBU1MnIDogJ0ZBSUwnOyA/PgogICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDx0ZD48P3BocCBlY2hvIGgoJGFscmVhZHlJbnN0YWxsZWQgPyAnTm90IG5lZWRlZCDigJQgdjAyNCBpbnN0YWxsZWQuJyA6IChzdHJpbmcpJGNhbmRpZGF0ZUxpbnRbJ291dHB1dCddKTsgPz48L3RkPgogICAgICAgICAgICA8L3RyPgogICAgICAgICAgICA8dHI+CiAgICAgICAgICAgICAgICA8dGQ+SW5zdGFsbGVkIFBIUCBsaW50PC90ZD4KICAgICAgICAgICAgICAgIDx0ZCBjbGFzcz0iPD9waHAgZWNobyAhZW1wdHkoJGluc3RhbGxlZExpbnRbJ29rJ10pID8gJ3Bhc3MnIDogJ2ZhaWwnOyA/PiI+CiAgICAgICAgICAgICAgICAgICAgPD9waHAgZWNobyAhZW1wdHkoJGluc3RhbGxlZExpbnRbJ29rJ10pID8gJ1BBU1MnIDogJ0ZBSUwnOyA/PgogICAgICAgICAgICAgICAgPC90ZD4KICAgICAgICAgICAgICAgIDx0ZD48P3BocCBlY2hvIGgoKHN0cmluZykkaW5zdGFsbGVkTGludFsnb3V0cHV0J10pOyA/PjwvdGQ+CiAgICAgICAgICAgIDwvdHI+CiAgICAgICAgICAgIDx0cj4KICAgICAgICAgICAgICAgIDx0ZD5Sb2xsYmFjayBiYWNrdXA8L3RkPgogICAgICAgICAgICAgICAgPHRkPjw/cGhwIGVjaG8gJGJhY2t1cEV4aXN0cyA/ICc8c3BhbiBjbGFzcz0icGFzcyI+UkVBRFk8L3NwYW4+JyA6ICc8c3BhbiBjbGFzcz0ibXV0ZWQiPk5vdCBjcmVhdGVkIHlldDwvc3Bhbj4nOyA/PjwvdGQ+CiAgICAgICAgICAgICAgICA8dGQ+PGNvZGU+PD9waHAgZWNobyBoKCRiYWNrdXBGaWxlKTsgPz48L2NvZGU+PC90ZD4KICAgICAgICAgICAgPC90cj4KICAgICAgICA8L3RhYmxlPgoKICAgICAgICA8ZGl2IGNsYXNzPSJidXR0b25zIj4KICAgICAgICAgICAgPGZvcm0gbWV0aG9kPSJwb3N0Ij4KICAgICAgICAgICAgICAgIDxpbnB1dCB0eXBlPSJoaWRkZW4iIG5hbWU9ImFjdGlvbiIgdmFsdWU9ImFwcGx5Ij4KICAgICAgICAgICAgICAgIDxidXR0b24gY2xhc3M9ImFwcGx5IiB0eXBlPSJzdWJtaXQiIDw/cGhwIGVjaG8gJGNhbkFwcGx5ID8gJycgOiAnZGlzYWJsZWQnOyA/Pj5BcHBseSB2MDI0PC9idXR0b24+CiAgICAgICAgICAgIDwvZm9ybT4KCiAgICAgICAgICAgIDxhIGNsYXNzPSJidG4gbmV1dHJhbCIgaHJlZj0iPD9waHAgZWNobyBoKGJhc2VuYW1lKCRfU0VSVkVSWydQSFBfU0VMRiddID8/ICcnKSk7ID8+Ij5SZWZyZXNoIC8gUHJlZmxpZ2h0PC9hPgogICAgICAgICAgICA8YSBjbGFzcz0iYnRuIG5ldXRyYWwiIGhyZWY9Ii90ZWFtX2NoYXJ0LnBocCIgdGFyZ2V0PSJfYmxhbmsiIHJlbD0ibm9vcGVuZXIiPk9wZW4gVGVhbSBDaGFydDwvYT4KCiAgICAgICAgICAgIDxmb3JtIG1ldGhvZD0icG9zdCIgb25zdWJtaXQ9InJldHVybiBjb25maXJtKCdSZXN0b3JlIHRoZSBiYWNrZWQtdXAgdjAyMyBUZWFtIENoYXJ0PycpOyI+CiAgICAgICAgICAgICAgICA8aW5wdXQgdHlwZT0iaGlkZGVuIiBuYW1lPSJhY3Rpb24iIHZhbHVlPSJyb2xsYmFjayI+CiAgICAgICAgICAgICAgICA8YnV0dG9uIGNsYXNzPSJyb2xsYmFjayIgdHlwZT0ic3VibWl0IiA8P3BocCBlY2hvICRiYWNrdXBFeGlzdHMgPyAnJyA6ICdkaXNhYmxlZCc7ID8+PlJvbGxiYWNrIFRlYW0gQ2hhcnQ8L2J1dHRvbj4KICAgICAgICAgICAgPC9mb3JtPgogICAgICAgIDwvZGl2PgogICAgPC9kaXY+CjwvZGl2Pgo8L2JvZHk+CjwvaHRtbD4K';

function h($v): string
{
    return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
}

function lint_php_file(string $path): array
{
    if (!function_exists('shell_exec')) {
        return ['ok'=>false,'output'=>'shell_exec() is not available.'];
    }

    $out = @shell_exec('php -l ' . escapeshellarg($path) . ' 2>&1');

    if ($out === null) {
        return ['ok'=>false,'output'=>'[NULL returned by shell_exec()]'];
    }

    $out = trim((string)$out);

    return ['ok'=>stripos($out,'No syntax errors detected') !== false,'output'=>$out];
}

$realPath = __DIR__ . '/' . REAL_FILE_NAME;
$action = (string)($_POST['action'] ?? '');
$message = '';
$messageClass = 'info';
$lint = null;

if ($action === 'stage') {
    $payload = base64_decode(REAL_FILE_B64, true);

    if ($payload === false) {
        $message = 'FAIL — embedded installer payload could not be decoded.';
        $messageClass = 'bad';
    } elseif (hash('sha256', $payload) !== REAL_FILE_SHA256) {
        $message = 'FAIL — embedded installer payload hash did not match.';
        $messageClass = 'bad';
    } else {
        if (is_file($realPath)) {
            $existing = (string)@file_get_contents($realPath);

            if (hash('sha256', $existing) !== REAL_FILE_SHA256) {
                $message = 'FAIL — a different file already exists with the installer filename. Nothing was overwritten.';
                $messageClass = 'bad';
            }
        }

        if ($message === '' && !is_file($realPath)) {
            if (@file_put_contents($realPath, $payload, LOCK_EX) === false) {
                $message = 'FAIL — could not stage the real installer.';
                $messageClass = 'bad';
            } else {
                @chmod($realPath, 0644);
            }
        }

        if ($message === '') {
            $lint = lint_php_file($realPath);

            if (!empty($lint['ok'])) {
                $message = 'PASS — real installer staged, hash-matched, and PHP lint passed.';
                $messageClass = 'good';
            } else {
                $message = 'FAIL — real installer was staged but did not pass PHP lint.';
                $messageClass = 'bad';
            }
        }
    }
}

if ($lint === null && is_file($realPath)) {
    $existing = (string)@file_get_contents($realPath);

    if (hash('sha256', $existing) === REAL_FILE_SHA256) {
        $lint = lint_php_file($realPath);
    }
}

$ready = is_file($realPath)
    && $lint !== null
    && !empty($lint['ok'])
    && hash_file('sha256', $realPath) === REAL_FILE_SHA256;
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MRL Team Chart Spreadsheet Border Fix Lint Gate</title>
<style>
:root{color-scheme:dark;--bg:#101010;--panel:#1b1b1b;--line:#3d3d3d;--text:#eee;--muted:#aaa;--good:#66df8d;--bad:#ff7474;--gold:#f2c98e}
*{box-sizing:border-box}
body{margin:0;padding:22px;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif}
.wrap{max-width:950px;margin:0 auto}
h1{color:var(--gold);margin:0 0 6px}
.card{margin:14px 0;padding:16px;background:var(--panel);border:1px solid var(--line);border-radius:14px}
.notice{margin:14px 0;padding:12px 14px;border-radius:10px;border:1px solid #36506f;background:#142033}
.notice.good{border-color:#327a4b;background:#13271a;color:#a8efbf}
.notice.bad{border-color:#983f3f;background:#2a1515;color:#ffb0b0}
.pass{color:var(--good);font-weight:800}.fail{color:var(--bad);font-weight:800}.muted{color:var(--muted)}
code{background:#282828;padding:2px 5px;border-radius:5px;word-break:break-all}
.buttons{display:flex;flex-wrap:wrap;gap:10px;margin-top:14px}
button,.btn{border:0;border-radius:9px;padding:10px 16px;color:white;font-weight:700;cursor:pointer;text-decoration:none;display:inline-block;font-size:14px}
.stage{background:#248c4b}.open{background:#276fca}
pre{white-space:pre-wrap;word-break:break-word;background:#111;border:1px solid #333;border-radius:10px;padding:12px}
</style>
</head>
<body>
<div class="wrap">
    <h1>MRL Team Chart Spreadsheet Border Fix Lint Gate</h1>
    <div class="muted">Generated 9/20/2026 3:23:48 pm ET</div>

    <?php if ($message !== ''): ?>
        <div class="notice <?php echo h($messageClass); ?>"><?php echo h($message); ?></div>
    <?php endif; ?>

    <div class="card">
        <h2>Real installer</h2>
        <p><code><?php echo h(REAL_FILE_NAME); ?></code></p>
    </div>

    <div class="card">
        <h2>Lint status</h2>

        <?php if ($ready): ?>
            <p class="pass">PASS — installer is staged, hash-matched, and lint-clean.</p>
        <?php elseif ($lint !== null): ?>
            <p class="fail">NOT READY — review lint result.</p>
        <?php else: ?>
            <p class="muted">Not staged yet.</p>
        <?php endif; ?>

        <?php if ($lint !== null): ?>
            <pre><?php echo h((string)$lint['output']); ?></pre>
        <?php endif; ?>

        <div class="buttons">
            <form method="post">
                <input type="hidden" name="action" value="stage">
                <button class="stage" type="submit">Stage + Lint Real Installer</button>
            </form>

            <?php if ($ready): ?>
                <a class="btn open" href="<?php echo h(REAL_FILE_NAME); ?>">Open Real Installer</a>
            <?php endif; ?>
        </div>
    </div>
</div>
</body>
</html>
